# Generated by Django 5.2.8 on 2025-11-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_company_slug_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
